lang: en

title: RAJAN YADAV   # Use BLOCK letters
avatar: "https://i.postimg.cc/VvzR1Jdb/Profile-Picture-Photo.jpg"
email: mail.rajanydv@gmail.com
description: >-
  Lorem Ipsum is simply dummy text of the printing and typesetting industry.
  Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.
baseurl: ""
url: ""

podcast_title: "Hatchedland Spoils a Movie"
podcast_description: "This podcast is here to take you deep into the depth some compelling stories, acting, direction, musical score, and other aspects of cinematography and what makes them stand out."
podcast_banner: "https://i.postimg.cc/RhSCnp4h/podcast-cover.png"

# socials
twitter_username: hatchedland
github_username:  hatchedland
lastfm_username: rajanyadav
linkedin_username: rajanydv
podbean_userid: user-R1vnlbi3jC2m

sass:
  sass_dir: _sass
  style: compressed

# website tabs
collections:
  podcasts:
    output: true
  casestudies:
    output: true
  projects:
    output: true


defaults:
  - scope:
      path: ''          # An empty string here means all files in the project
      type: casestudies
    values:
      layout: casestudy
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /casestudies/:title/
  - scope:
      path: ''          # An empty string here means all files in the project
      type: projects
    values:
      layout: projects
      comments: true   
      toc: true 
      permalink: /projects/:title/
  - scope:
      path: ''          # An empty string here means all files in the project
      type: podcasts
    values:
      layout: podcast
      comments: true   
      toc: true 
      permalink: /podcasts/:title/

# Build settings
theme: nuboard-theme
# plugins:
  # - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
